name: CI / CD Pipeline

on:
  push:
    branches:
      - master
      - feature/**
  pull_request:
    branches:
      - master
      - develop
      - release
      
jobs:
  build:
    name: Executando o job de build do projeto
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        run: dotnet restore
        working-directory: src

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: src

  unit-tests:
    name: Executando o job de testes unitário
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        run: dotnet restore
        working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.UnitTests

      - name: Build
        run: dotnet build --configuration Release --no-restore 
        working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.UnitTests

      - name: Run unit tests
        run: dotnet test --configuration Release --no-restore --verbosity normal 
        working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.UnitTests
  
  integration-tests:
    name: Executando o job de testes de integração
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        run: dotnet restore
        working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.IntegrationTests

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.IntegrationTests

      - name: Run integration tests
        run: dotnet test --configuration Release --no-restore --verbosity normal
        working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.IntegrationTests
  
  functional-tests:
    name: Executando o job de testes funcionais
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: Install dependencies
        run: dotnet restore
        working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.FunctionalTests

      - name: Build
        run: dotnet build --configuration Release --no-restore
        working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.FunctionalTests

      - name: Run functional tests
        run: dotnet test --configuration Release --no-restore --verbosity normal
        working-directory: tests/Postech.PhaseOne.GroupEight.TechChallenge.FunctionalTests

  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        # Disabling shallow clones is recommended for improving the relevancy of reporting
        fetch-depth: 0
    - name: SonarQube Scan
      uses: sonarsource/sonarqube-scan-action@v2.1.0
      with:
        projectBaseDir: src
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}
